<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4khAuie' shared service.

return $this->privates['.service_locator.4khAuie'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tokenStorage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
], [
    'tokenStorage' => '?',
]);
