<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eybLktC' shared service.

return $this->privates['.service_locator.eybLktC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'notification' => ['privates', '.errored..service_locator.eybLktC.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.eybLktC": it references class "App\\Entity\\Notification" but no such service exists.'],
], [
    'notification' => 'App\\Entity\\Notification',
]);
