<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GJI9TYt' shared service.

return $this->privates['.service_locator.GJI9TYt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userWithPosts' => ['privates', '.errored..service_locator.GJI9TYt.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.GJI9TYt": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'userWithPosts' => 'App\\Entity\\User',
]);
