<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\BlogController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/BlogController.php';

return $this->services['App\\Controller\\BlogController'] = new \App\Controller\BlogController(($this->services['twig'] ?? $this->getTwigService()), ($this->services['session'] ?? $this->load('getSessionService.php')), ($this->services['router'] ?? $this->getRouterService()));
