<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jwnq._3' shared service.

return $this->privates['.service_locator.jwnq._3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'tokenGenerator' => ['privates', 'App\\Security\\TokenGenerator', 'getTokenGeneratorService.php', true],
], [
    'eventDispatcher' => '?',
    'passwordEncoder' => '?',
    'tokenGenerator' => 'App\\Security\\TokenGenerator',
]);
