<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QoOem..' shared service.

return $this->privates['.service_locator.QoOem..'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tokenStorage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'tokenStorage' => '?',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
