<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\MicroPostController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/MicroPostController.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/Session/SessionBagInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/Session/Flash/FlashBagInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/Session/Flash/FlashBag.php';

return $this->services['App\\Controller\\MicroPostController'] = new \App\Controller\MicroPostController(($this->services['twig'] ?? $this->getTwigService()), ($this->privates['App\\Repository\\MicroPostRepository'] ?? $this->load('getMicroPostRepositoryService.php')), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->privates['session.flash_bag'] ?? ($this->privates['session.flash_bag'] = new \Symfony\Component\HttpFoundation\Session\Flash\FlashBag())), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
