<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\TokenGenerator' shared autowired service.

include_once $this->targetDirs[3].'/src/Security/TokenGenerator.php';

return $this->privates['App\\Security\\TokenGenerator'] = new \App\Security\TokenGenerator();
