<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Event\UserSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/Event/UserSubscriber.php';
include_once $this->targetDirs[3].'/src/Mailer/Mailer.php';

return $this->privates['App\\Event\\UserSubscriber'] = new \App\Event\UserSubscriber(new \App\Mailer\Mailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['twig'] ?? $this->getTwigService()), $this->getEnv('MAILER_FROM')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), 'en');
