<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Event\UserLocaleSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/Event/UserLocaleSubscriber.php';

return $this->privates['App\\Event\\UserLocaleSubscriber'] = new \App\Event\UserLocaleSubscriber(($this->services['session'] ?? $this->load('getSessionService.php')));
