<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTVxsDh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTVxsDh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTVxsDh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTVxsDh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXTVxsDh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XTVxsDh',
    'container.build_id' => '64a36b24',
    'container.build_time' => 1575249507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTVxsDh');
